name: Deploy Static Files

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Dev
        run: |
          echo "Deploying to Dev environment at ${{ secrets.DEV_URL }}"
          # Add your deployment script/commands here

  deploy-uat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to UAT
        run: |
          echo "Deploying to UAT environment at ${{ secrets.UAT_URL }}"
          # Add your deployment script/commands here