name: Deploy

on:
  push:
    branches:
      - main
      - dev
      - uat

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Dev
        env:
          DEV_URL: ${{ secrets.DEV_URL }}
        run: |
          echo "Deploying to Dev environment at $DEV_URL"
    

  deploy-uat:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to UAT
        env:
          UAT_URL: ${{ secrets.UATURL }}
        run: |
          echo "Deploying to UAT environment at $UAT_URL"
          