name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - dev
      - uat

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Dev, UAT]
    
    environment: ${{ matrix.environment }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Deployment URL
        run: |
          if [[ "${{ matrix.environment }}" == "Dev" ]]; then
            echo "DEPLOY_URL=${{ secrets.DEV_URL }}" >> $GITHUB_ENV
          elif [[ "${{ matrix.environment }}" == "UAT" ]]; then
            echo "DEPLOY_URL=${{ secrets.UAT_URL }}" >> $GITHUB_ENV
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: .
 